### ISSUE TITLE
Improve the user registration process 

### ISSUE THREAD

**Issue by matthewbub** [matthewbub/pdftocsv#93]
We should allow the use of `_ | - | .` in usernames. We should also improve the error messaging on the client if the username criteria is not met. We could do this using recat-hook-form

This is where we check the form data on the server https://github.com/matthewbub/zcauldron/blob/540681936da2f5feda65d713aa18acc16fc94ffd/pkg/api/sign_up.go#L36

and this is where we implement the sign up form on the UI https://github.com/matthewbub/zcauldron/blob/540681936da2f5feda65d713aa18acc16fc94ffd/routes/src/routes/sign-up.tsx#L82

**Comment by matthewbub** [comment]
@AndrewDucNguyen on the server, I think we can update the validate username method to consume this regex pattern `^[a-zA-Z0-9._-]{3,30}$` and then on the client in the sign up form we can use this React-hook-form confirm object

```ts
{...register("username", {
    required: "Username is required",
    pattern: {
        value: /^[a-zA-Z0-9._-]{3,30}$/,
        message: "Username must be 3-30 characters and can only contain letters, numbers, dots, hyphens, and underscores"
    },
    validate: {
        noConsecutiveSpecials: (value) => {
            // Prevent consecutive special characters
            if (/[._-]{2,}/.test(value)) {
                return "Special characters (. _ -) cannot be consecutive";
            }
            return true;
        },
        noSpecialsAtEnds: (value) => {
            // Prevent special characters at start/end
            if (/^[._-]|[._-]$/.test(value)) {
                return "Username cannot start or end with special characters";
            }
            return true;
        }
    }
})}
```

**Comment by AndrewDucNguyen** [comment]
@matthewbub put in a PR for this issue 💯
